
# ============================================================
# Google Drive API Settings
# ============================================================
google_drive:

  # Path to your Google OAuth client credentials JSON file.
  # Download from Google Cloud → API & Services → Credentials.
  credentials_file: ./Json/credentials.json

  # Whether to save the OAuth access token to disk.
  # If True, token.json is created and reused on next runs.
  save_token: True

  # Path to store the generated OAuth token (token.json).
  # Only used when save_token=True.
  save_token_file: ./Json/token.json

  # OAuth scopes required by the script.
  # "drive.file" allows uploading and modifying your own files.
  oauth_scope:
    - https://www.googleapis.com/auth/drive.file

  # Whether to use remote authentication
  remote: False


# ============================================================
# Proxy Settings
# ============================================================
  # Proxy server used for Google Drive upload (optional).
  # Supported formats:
  #   - 127.0.0.1:1080
  #   - http://127.0.0.1:1080
  #   - socks4://127.0.0.1:1080
  #   - socks5://127.0.0.1:1080
  # If null, no proxy is used.
proxy: null # socks://127.0.0.1:1080

# ============================================================
# Log Settings
# ============================================================
  # Log file name.
  # If null, log messages are printed to console only.
log: null


# ============================================================
# Upload Settings
# ============================================================
upload:
  # Local file path or list of local files to upload.
  # Examples:
  #   - "data.zip"
  #   - ["a.txt", "b.txt"]
  # If null, must be provided by CLI argument -n / --name.
  local_file: ['settings.yaml', 'requirements.txt']

  # The filename(s) to be used in Google Drive.
  # If null, Google Drive will use the local filename(s) by default.
  # Must match the length of local_file if both are lists.
  save_file_name: null

  # The target folder ID in Google Drive.
  # If null, uploads to the root directory ("My Drive").
  save_folder_id: null

  # Chunk size for resumable upload in bytes.
  # Default chunk size 10MB (1024*1024*10).
  chunksize: 10485760


# ============================================================
# Download Settings
# ============================================================
download:

  # Local directory to save downloaded files.
  # If null, files are saved to the './download'.
  save_local_dir: './download'

  # The file id(s) to download from Google Drive.
  # Examples:
  #   - "1A2B3C4D5E6F7G8H9I0J"
  #   - ["1A2B3C4D5E6F7G8H9I0J", "0J9I8H7G6F5E4D3C2B1A"]
  # Must match the length of save_local_file if both are lists.
  file_id: file_id

  # Chunk size for resumable download in bytes.
  # Default chunk size 10MB (1024*1024*10).
  chunksize: 10485760


